export const environment = {
  production: true,
  host: '',
  creds: 'ajax=true',
  assets: '/assets/angular/',
  login: '/api/login',
  signup: '/api/signup',
  ulogout: '/ulogout',
  checkAuth: '/api/user/check-auth',
  uploadTrackList: '/upload',
  uploadFilesUrl: '/api/track-upload/upload-track-file',
  musicList: '/music',
  uploadTrackImage: '/crop/index/trackImg',
  uploadDetails: '/upload_details',
  uploadTrackInfo: '/api/track-upload/upload-track-info',
  saveTrack: '/save_track',
  browse: '/browse',
  browseNewSongs:  '/browse/new-songs',
  browsePopularArtist: '/browse/popular-artist'
};
